CREATE TABLE EMPLOYEE (
    EMPLOYEE_ID INTEGER PRIMARY KEY,
    EMP_FIRSTNAME VARCHAR(20) NOT NULL,
    EMP_LASTNAME VARCHAR(20) NOT NULL,
    DEPARTMENT_ID INTEGER NOT NULL,
    SALARY INTEGER NOT NULL,
    EMP_EMAIL VARCHAR(40)
);

CREATE TABLE DEPARTMENT (
    DEPARTMENT_ID INTEGER PRIMARY KEY,
    DEPARTMENT_NAME VARCHAR(40)
);
--SEQUENCES
CREATE SEQUENCE SQ_EMP_PK
START WITH 1000
INCREMENT BY 10;

CREATE SEQUENCE SQ_DEPT_PK
START WITH 1111
INCREMENT BY 10;

--TRIGGERS
CREATE OR REPLACE TRIGGER TR_INSERT_EMP_ID
BEFORE INSERT ON EMPLOYEE
FOR EACH ROW
BEGIN
    SELECT SQ_EMP_PK.NEXTVAL INTO :NEW.EMPLOYEE_ID FROM DUAL;
 END;
 
CREATE OR REPLACE TRIGGER TR_INSERT_DEPT_ID
BEFORE INSERT ON DEPARTMENT
FOR EACH ROW
BEGIN
    SELECT SQ_DEPT_PK.NEXTVAL INTO :NEW.DEPARTMENT_ID FROM DUAL;
 END;

--INSERTS
INSERT INTO DEPARTMENT(DEPARTMENT_NAME)
VALUES('Sales');

INSERT INTO DEPARTMENT(DEPARTMENT_NAME)
VALUES('HR');

INSERT INTO DEPARTMENT(DEPARTMENT_NAME)
VALUES('IT');

INSERT INTO EMPLOYEE (EMP_FIRSTNAME, EMP_LASTNAME, DEPARTMENT_ID, SALARY, EMP_EMAIL)
VALUES ('Mike', 'Ross', 1111, 60000, 'mross@gmail.com');

INSERT INTO EMPLOYEE (EMP_FIRSTNAME, EMP_LASTNAME, DEPARTMENT_ID, SALARY, EMP_EMAIL)
VALUES ('Rachel', 'Kim', 1111, 50000, 'rkim@gmail.com');

INSERT INTO EMPLOYEE (EMP_FIRSTNAME, EMP_LASTNAME, DEPARTMENT_ID, SALARY, EMP_EMAIL)
VALUES ('Sally', 'Smith', 1121, 40000, 'ssmith@gmail.com');

INSERT INTO EMPLOYEE (EMP_FIRSTNAME, EMP_LASTNAME, DEPARTMENT_ID, SALARY, EMP_EMAIL)
VALUES ('Don', 'Brown', 1121, 60000, 'dbrown@gmail.com');

INSERT INTO EMPLOYEE (EMP_FIRSTNAME, EMP_LASTNAME, DEPARTMENT_ID, SALARY, EMP_EMAIL)
VALUES ('Kevin', 'Lee', 1131, 80000, 'klee@gmail.com');

INSERT INTO EMPLOYEE (EMP_FIRSTNAME, EMP_LASTNAME, DEPARTMENT_ID, SALARY, EMP_EMAIL)
VALUES ('Dave', 'Scott', 1131, 75000, 'dscott@gmail.com');

--PROCEDURE
CREATE OR REPLACE PROCEDURE SP_GIVE_RAISE(DEPT_ID IN INTEGER)
AS
AVGSAL NUMBER(8,2);
BEGIN
    UPDATE EMPLOYEE SET SALARY = (SALARY * 1.1)
    WHERE DEPT_ID = DEPARTMENT_ID;
    
    SELECT AVG(SALARY) 
    INTO AVGSAL
    FROM EMPLOYEE;
    
END;

begin
sp_give_raise(1111);
end;